site_name: dom
site_url: https://domothy.com/
docs_dir: content
site_dir: docs
theme:
  name: material
  custom_dir: 'theme/'
  logo: assets/images/pentagonboi.png
  palette:
    - scheme: default
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - scheme: slate
      primary: black
      accent: red
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
extra:
  social:
    - name: twitter
      link: https://twitter.com/domothy
      icon: fontawesome/brands/twitter
    - name: reddit
      link: https://www.reddit.com/user/domotheus
      icon: fontawesome/brands/reddit
    - name: telegram
      link: https://t.me/domothy
      icon: fontawesome/brands/telegram
    - name: github
      link: https://github.com/domothyb
      icon: fontawesome/brands/github
    - name: ethereum
      link: https://etherscan.io/address/domothy.eth
      icon: fontawesome/brands/ethereum
    - name: email
      link: mailto:domothyb@protonmail.com
      icon: fontawesome/regular/envelope